import { API_KEY, PASSWORD } from 'react-native-dotenv';

export const apiKey = API_KEY;
export const adminPW = PASSWORD;

export const FORM_USER_INFO = {
  FORM_USER_INFO_NAME: 'FORM_USER_INFO_NAME', FORM_USER_INFO_EMAIL: 'FORM_USER_INFO_EMAIL',
  FORM_USER_INFO_SATISFACTION: 'FORM_USER_INFO_SATISFACTION', 
  FORM_USER_INFO_POSITION: 'FORM_USER_INFO_POSITION',
  FORM_USER_INFO_SALARY: 'FORM_USER_INFO_SALARY',
  FORM_USER_INFO_OPINION: 'FORM_USER_INFO_OPINION'
};

export const ADMIN_PASSWORD = {
  ADMIN_PASSWORD_INPUT: 'ADMIN_PASSWORD_INPUT'
};